config/routes.rb
CrowdRank::Application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'signin', :sign_out => 'signout'}

  get "users/new"

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'

  resources :users do
    resources :rankings
  end

  resources :team_groups, path: "leagues"

  resources :user_groups, path: "groups"

  

end

app/models/composite_rank.rb
class CompositeRank < ActiveRecord::Base
	belongs_to :composite_ranking
	belongs_to :team
end

app/models/composite_ranking.rb
class CompositeRanking < ActiveRecord::Base
	has_many :composite_ranks, dependent: :destroy
	belongs_to :user
	belongs_to :team_group
end

app/models/rank.rb
class Rank < ActiveRecord::Base
	belongs_to :ranking
	belongs_to :team
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
	has_many :ranks, dependent: :destroy
	belongs_to :user
	belongs_to :team_group
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_and_belongs_to_many :team_groups
end

app/models/team_group.rb
class TeamGroup < ActiveRecord::Base
	has_and_belongs_to_many :teams
	has_and_belongs_to_many :user_groups
	has_ancestry

	def to_param
		short_name if root?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  before_save { self.email = email.downcase }

  validates :password, length: { minimum: 6 }

  has_many :user_group_subscriptions
  has_many :user_groups, through: :user_group_subscriptions
  has_many :rankings
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	has_many :user_group_subscriptions
	has_many :users, through: :user_group_subscriptions
	has_and_belongs_to_many :team_groups
end

app/models/user_group_subscription.rb
class UserGroupSubscription < ActiveRecord::Base
	belongs_to :user
	belongs_to :user_group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
    	u.permit!
    end
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController

	def create
		# This doesn't need to be a super responsive action,
		# but if speed becomes a problem, maybe consider raw SQL
		# for a multi query
		# It wouldn't be the craziest thing in the world for it
		# to kick off a job either, and render a result page straight
		# from the JSON

		ranking_json = JSON.parse(params[:ranking_json])
		team_group_id = params[:ranking][:team_group]

		ActiveRecord::Base.transaction do
			ranking = Ranking.create!(user_id: current_user.id, team_group_id: team_group_id)

			ranks_list = []
			ranking_json.each do |team_id, data|
				ranks_list << { team_id: team_id,
												value: data['rank'],
												comment: data['comment'],
												ranking_id: ranking.id}
			end
		end
		Rank.create!(ranks_list)

		redirect_to TeamGroup.find(team_group_id)
	end

	def new
		@team_group = params[:team_group]
		@team_group = TeamGroup.find_by_short_name("NFL") # fake line for now; rankings/new should be a GET with a team_group_id in URL

		@teams = CompositeRanking.where(team_group_id: @team_group.id).order(:period_end_at).last.composite_ranks.map { |cr| cr.team }
	end

	def show
		@ranking = Ranking.includes(:ranks).find(params[:id])
		@ranks = @ranking.ranks.order(:value)

		@user = User.find(@ranking.user_id)

		@last_ranking = Ranking.includes(:ranks).where("team_group_id = ? AND
																										user_id = ? AND
																										created_at < ?", @ranking.team_group_id, @user.id, @ranking.created_at).order(:created_at).last
		@last_ranks = @last_ranking.ranks.order(:value)

		@diffs = {}
		@ranks.each do |r|
			@diffs[r.team_id] = @last_ranks.where(team_id: r.team_id).first.value - r.value
		end
		
		puts "-----------------------------"
		puts @last_ranks.where(team_id: 7).first.team.id
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
  def home
  end

  def help
  end
end

app/controllers/team_groups_controller.rb
require "#{Rails.root}/app/helpers/date_helper"
include DateHelper

class TeamGroupsController < ApplicationController

	def show
		@team_group = TeamGroup.includes(:teams).find_by_short_name(params[:id])
		@user_group = params[:user_group] ? UserGroup.find(params[:user_group]) : UserGroup.find_by_name("Everyone")

		@series = []
		# Load team data (nicknames, colors) from db
		@team_group.teams.order(:nickname).each do |team|
			@series << { id: team.id, name: team.nickname, color: team.primary_color, data: [], marker: { enabled: false, symbol: 'circle' } }
		end

		# Load teams and visions from db for easy chart modification
		@child_team_groups = @team_group.descendants.includes(:teams)
		@team_group_team_ids = {}
		@child_team_groups.each do |tg|
			@team_group_team_ids[tg.id] = tg.teams.map { |t| t.id }
		end

		# Load composite ranking data from db
		composite_rankings = CompositeRanking.includes(:composite_ranks).where(team_group_id: @team_group.id, user_group_id: @user_group.id).order(:period_start_at)
		@time_periods = []
		composite_rankings.each do |cr|
			@time_periods << cr.period_start_at.to_date.strftime('%b %e')
			cr.composite_ranks.each do |r|
				@series.find { |s| s[:id] == r.team_id }[:data] << r.value
			end
		end

		# Calculate biggest movers
		movement = {}
		composite_rankings[-2].composite_ranks.each do |r|
			movement[r.team_id] = r.value
		end
		composite_rankings.last.composite_ranks.each do |r|
			movement[r.team_id] = movement[r.team_id] - r.value
		end

		teams_by_change = movement.sort_by { |team, val| val }
		@biggest_uppers = teams_by_change.last(3).reverse
		@biggest_downers = teams_by_change.first(3)
	end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController

	def show
		@user_group = UserGroup.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all.to_a
	end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		sign_in @user
      user_group = UserGroup.find_by_name("Everyone")
      @user.user_groups << user_group
  		flash[:success] = "Success"
  		redirect_to root_url
  	else
  		render root_url
  	end
  end

  def show
    @user = User.find(params[:id])
    @rankings = Ranking.where(user_id: params[:id])
  end


  private

  	def user_params
  		params.require(:user).permit(:username, :email, :password, :password_confirmation)
  	end

  	def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/date_helper.rb
module DateHelper

	 # Given a date, get, say, last tuesday
  def current_or_last_day_of_week(day_of_week, time = DateTime.now)
		if time.wday == day_of_week
			time.beginning_of_day
		else
			time_iter = time
			while time_iter.wday != day_of_week do
				time_iter = time_iter - 1.day
			end
			time_iter.beginning_of_day
		end
	end
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_group_helper.rb
module TeamGroupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rankings/new.html.erb
<div class="well centered-text">
	<h2><%= @team_group.short_name %></h2>
	<small>as of <%= Date.today %></small>

	<%= form_for :ranking, url: { action: "create" }, html: { id: 'ranking_form' } do |f| %>
	<div>
    <%= f.submit "Rank", class: "btn btn-large btn-success", id: "rank_button" %>
    <%= f.text_field "team_group", type: "hidden", value: @team_group.id %>
  </div>
</div>

<div class="row marketing">
	<div class="col-lg-6">
		<ul id="teams" class="list-group span4">
			<% @teams.each do |t| %>
				<li class="list-group-item" id="team <%= t.id %>">
					<%= t.nickname %>
					<%= f.text_field "comment_#{t.id}", class: "pull-right" %>
				</li>
			<% end %>
		</ul>
	</div>
</div>
	<% end %>

<script type="text/javascript">
$(function() {

	$("#teams").sortable({
		cancel: ".already-ranked"
	});
	$('#teams input').bind('click.sortable mousedown.sortable',function(e){
    e.target.focus();
  });

	$("#rank_button").click(function () {
		//var ranks = $("#teams").sortable("toArray");
		var ranks = $(".list-group-item");
		var rankings_json = {};
		var actual_rank = 0;
			for (var i = ranks.length - 1; i >= 0; i--) {
				actual_rank++;
				var team_id = ranks[i].id.split(" ")[1];
				var comment = $("#ranking_comment_" + team_id).val();
				rankings_json[team_id] = {
					rank: actual_rank,
					comment: comment
				};
			};
		

		$('<input>').attr({
			type: 'hidden',
			id: 'json',
			name: 'ranking_json',
			value: JSON.stringify(rankings_json)
		}).appendTo('#ranking_form');
	});
});
</script>

app/views/rankings/show.html.erb
<div class="row" id="main">
  <div class="col-sm-4">
  	<%= @user.username %>
  	<%= @ranking.team_group_id %>
  </div>
  <div class="col-sm-8" id="ranking-col">
  	<% @ranks.each do |r| %>
  		<%= r.value %>
  		<%= r.team.nickname %>
  		<% if @diffs[r.team_id] < 0 %>
  			<%= fa_icon "caret-down lg", text: @diffs[r.team_id] %>
  		<% elsif @diffs[r.team_id] > 0 %>
  			<%= fa_icon "caret-up lg", text: @diffs[r.team_id] %>
  		<% else %>
  			-
  		<% end %>
  		<p class="comment"><%= r.comment %></p>
  		<br>
  	<% end %>
  </div>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
	<div class="container">
		<h1>Welcome!</h1>
		<p>The Crowd Rank is a website for power ranking nerds of every sporting persuasion.  Rank the leauges you follow and track the ratings of friends and pundits to answer the question of who's the consensus favorite (or flop).</p>
		<p>The Crowd Rank is in development, so feel free to explore existing features and existing data, but <strong>any submitted data may be lost</strong>.  To see ratings, check out your favorite league above and sign up to rank.</p>
	</div>
</div>

app/views/team_groups/show.html.erb
<div class="well">
	<div class="row-fluid">
		<h2 class="text-center"><%= @team_group.full_name %></h2>
		<h4 class="text-center">Group: <%= link_to @user_group.name, @user_group %></h4>
		<div class="text-center">
			<% if user_signed_in? %>
				<%= button_to "Rank", new_user_ranking_path(current_user.id), :method => "get", class: "btn btn-large btn-success" %>
			<% else %>
				<button href="#" class="btn btn-large btn-default text-center">Sign up to rank!</button>
			<% end %>
			<br><br>
		</div>
		<div class="well" id="movers">
			<% @biggest_uppers.each do |team, val| %>
				<span class="mover">
					<b><%= Team.find(team).nickname %></b>
					<%= fa_icon "caret-up 2x", text: val %>
				</span>
			<% end %>
			<% @biggest_downers.each do |team, val| %>
				<span class="mover">
					<b><%= Team.find(team).nickname %></b>
					<%= fa_icon "caret-down 2x", text: val %>
				</span>
			<% end %>
		</div>
		<div id="highchart"></div>
	</div>
</div>

<div class="btn-toolbar">
	<div class="btn-group btn-group-sm">
		<button id="show_all" class="btn btn-default">Show all Teams</button>
		<button id="hide_all" class="btn btn-default">Hide all Teams</button>
	</div>
	<div class="btn-group btn-group-sm dropup">
		<button class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
			View Groups     <span class="caret"></span>
		</button>
		<ul class="dropdown-menu">
			<% @child_team_groups.each do |l| %>
				<li>
					<a id="<%= l.id.to_s + '_team_group_view' %>" class="team_group_view">
						<%= l.short_name %>
					</a>
				</li>
			<% end %>
		</ul>
	</div>
</div>

<script type="text/javascript">
$(function() {

	var options = {
	  chart: {
	    renderTo: 'highchart',
	    type: 'spline'
	  },
	  title: {
	    text: '<%= @team_group.short_name.to_s %>' + ' Rankings'
	  },
	  xAxis: {
	    categories: <%= raw @time_periods.to_json %>
	  },
	  yAxis: {
	    title: {
	      text: 'Rank'
	    },
	    reversed: true,
	    min: 0,
	    max: 32
	  },
	  series: <%= raw @series.to_json %>
	};

	chart = new Highcharts.Chart(options);

	show_all = function() {
		for (var i = 0; i < options.series.length; i++) {
			chart.get(options.series[i].id).setVisible(true, false)
		}
	};

	hide_all = function() {
		for (var i = 0; i < options.series.length; i++) {
			chart.get(options.series[i].id).setVisible(false, false)
		}
	};

	$("#show_all").click(show_all);

	$("#hide_all").click(hide_all);

	$(".team_group_view").click(function(e) {
		hide_all();

		var team_ids = team_group_team_ids[e.target.id.split("_")[0]]
		for (var i = 0; i < team_ids.length; i++) {
			chart.get(team_ids[i]).setVisible(true, false);
		}
	});

	var team_group_team_ids = <%= raw @team_group_team_ids.to_json %>;

});
</script>

app/views/user_groups/show.html.erb
<h2><%= @user_group.name %></h2>

<ul>
	<% @user_group.users.each do |u| %>
		<li class="list-group-item"><%= link_to u.username, u %></li>
	<% end %>
</ul>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
<fieldset>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, autofocus: true, class: "input-small" %></div>

  <div><%= f.label :username %><br />
  <%= f.text_field :username %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password, placeholder: "8 characters at least..." %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, placeholder: "Uno mas" %></div>

  <div><%= f.submit "Sign up" %></div>
 </fieldset>
<% end %>

<%= render "devise/shared/links" %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-4"><h3><%= @user.username %></h3></div>
  <div class="col-sm-8">
  	<% @rankings.each do |r| %>
  		<%= link_to r.created_at, user_ranking_path(@user, r) %>
  		<br>
  	<% end %>
  </div>
</div>